#!/bin/bash

## bash.exeで日本語が使える状態にする
export LANG=ja_JP.UTF-8

## ----<xming settings>----
export DISPLAY=localhost:0.0
function runx() {
    PROCESS_EXPR='x(launch|ming)'
    X_PROCESS=$(powershell "tasklist.exe | Select-String -Pattern \"${PROCESS_EXPR}\"")
    if [ $(echo ${X_PROCESS} | egrep -ie ${PROCESS_EXPR} | wc -l) -ge 1 ]; then
        echo "xlaunch.exe is already started."
    else
        echo "Starting xlaunch.exe"
        xlaunch.exe -run ~/config.xlaunch &
    fi
}
runx

function upload_over_ssh() {
  START_TIME=`date +%s`
  echo "tar czf - -C $1 $2 | ssh $3 'tar zxvf - -C $4'"
  tar czf - -C $1 $2 | ssh $3 "tar zxvf - -C $4"
  END_TIME=`date +%s`
  echo Execution time: $((END_TIME - START_TIME))
}

function download_over_ssh() {
  START_TIME=`date +%s`
  echo "ssh $1 'tar czf - -C $2 $3' | tar zxvf - -C $4"
  ssh ${1} "tar czf - -C $2 $3" | tar zxvf - -C $4
  END_TIME=`date +%s`
  echo Execution time: $((END_TIME - START_TIME))
}
