#!/bin/bash

## bash.exeで日本語が使える状態にする
export LANG=ja_JP.UTF-8

## ----<xming settings>----
export DISPLAY=localhost:0.0
function runx() {
    PROCESS_EXPR='x(launch|ming)'
    X_PROCESS=$(powershell "tasklist.exe | Select-String -Pattern \"${PROCESS_EXPR}\"")
    if [ $(echo ${X_PROCESS} | egrep -ie ${PROCESS_EXPR} | wc -l) -ge 1 ]; then
        echo "xlaunch.exe is already started."
    else
        echo "Starting xlaunch.exe"
        xlaunch.exe -run ~/config.xlaunch &
    fi
}
runx
